--Q1. What is the total revenue generated by male vs. female customers?
Select gender,sum(purchase_amount) as revenue from customers
group by gender ;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from customers
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount) from customers)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,ROUND(avg(review_rating :: numeric),2) as review
from customers
group by item_purchased
order by review desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
Select shipping_type,avg(purchase_amount) as AVG_PURCHASE_AMOUNT
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue  between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by total_revenue,avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
-- Customer segmentation 
with customer_type as (
select customer_id,previous_purchases,
CASE 
	WHEN previous_purchases =1 Then 'New'
	When previous_purchases BETWEEN 2 AND 10 Then 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
	from customers
)
Select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
with item_counts as (
SELECT category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC) as item_rank
from customers
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repet_buyers
from customers
where previous_purchases >5
group by subscription_status



--Q10. What is the revenue contribution of each age group? 
select age_grouped ,sum(purchase_amount) as total_revenue
from customers
group by age_grouped 
order by total_revenue desc;
